# Generated by Django 6.0.4 on 2026-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('import_type', models.CharField(choices=[('STUDENT_CREATION', "Création d'étudiants"), ('ENROLLMENT', 'Inscription')], default='STUDENT_CREATION', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], max_length=50)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='import_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
