# Generated by Django 6.0.4 on 2026-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
