# Generated by Django 6.0.4 on 2026-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_importjob_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], max_length=50),
        ),
    ]
