services:

  backend:
    build: ./backend
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  celery:
    build: ./backend
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - backend
    env_file:
      - ./backend/.env
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"