# Generated by Django 6.0.4 on 2026-05-27 05:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('NORMAL', 'normale'), ('RETAKE', 'rattrapage')], default='NORMAL', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('grade_weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('original_score', models.PositiveIntegerField()),
                ('original_status', models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATEDA_AFTER_RETAKE', 'validé apres rattrapage')])),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('VALIDATED', 'Validé'), ('NOT_VALIDATED', 'Échoué')], default='ACTIVE', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['semester__order', 'opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_repeated', models.BooleanField(default=False)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATEDA_AFTER_RETAKE', 'validé apres rattrapage')], default='NOT_VALIDATED')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
    ]
