# Generated by Django 6.0.4 on 2026-05-02 06:25

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0004_coursemodule_min_val_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('NORMAL', 'normale'), ('RETAKE', 'rattrapage')], default='NORMAL', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('grade_weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='structures.coursemodule')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='structures.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATEDA_AFTER_RETAKE', 'validé apres rattrapage')], default='NOT_VALIDATED')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_results', to='structures.coursemodule')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_results', to='structures.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='structures.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'assessment')},
            },
        ),
    ]
