# Generated by Django 6.0.4 on 2026-05-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='structures.coursemodule'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='structures.schoolyear'),
        ),
        migrations.AddField(
            model_name='enrollmentresult',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_results', to='structures.coursemodule'),
        ),
        migrations.AddField(
            model_name='enrollmentresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_results', to='structures.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='structures.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'assessment')},
        ),
    ]
