# Generated by Django 6.0.4 on 2026-05-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='structures.coursemodule'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='structures.schoolyear'),
        ),
        migrations.AddField(
            model_name='debt',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='structures.coursemodule'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.formation'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='structures.schoolyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='assessments.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentresult',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_results', to='structures.coursemodule'),
        ),
        migrations.AddField(
            model_name='enrollmentresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_results', to='assessments.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together={('enrollment', 'course_module')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'assessment')},
        ),
    ]
