# Generated by Django 6.0.4 on 2026-06-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('structures', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='last_deliberation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structures.schoolyear'),
        ),
    ]
