# Generated by Django 6.0.4 on 2026-05-11 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('structures', '0003_alter_coursemodule_credits_alter_schoolyear_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentresult',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(default=datetime.date(2026, 5, 11)),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField(default=False)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='structures.coursemodule')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='structures.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'course_module')},
            },
        ),
    ]
