# Generated by Django 6.0.4 on 2026-06-09 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(blank=True, default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
