# Generated by Django 6.0.4 on 2026-05-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_enrollmentresult_is_repeated_alter_assessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
