# Generated by Django 6.0.4 on 2026-06-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_grade_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_results', to='assessments.enrollment'),
        ),
    ]
