# Generated by Django 6.0.4 on 2026-06-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_enrollmentresult_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='original_status',
            field=models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATED_AFTER_RETAKE', 'validé apres rattrapage')]),
        ),
        migrations.AlterField(
            model_name='enrollmentresult',
            name='status',
            field=models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATED_AFTER_RETAKE', 'validé apres rattrapage')], default='NOT_VALIDATED'),
        ),
    ]
