# Generated by Django 6.0.4 on 2026-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='original_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='original_status',
            field=models.CharField(choices=[('NOT_VALIDATED', 'non validé'), ('VALIDATED', 'validé'), ('VALIDATEDA_AFTER_RETAKE', 'validé apres rattrapage')], default='NOT_VALIDATED'),
        ),
    ]
