# Generated by Django 6.0.3 on 2026-04-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0002_initial'),
        ('users', '0002_matriculecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('course_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='structures.coursecomponent')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='structures.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='users.teacheruser')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='structures.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.teacheruser')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('teacher', 'semester', 'day', 'start_time')},
            },
        ),
    ]
