# Generated by Django 6.0.4 on 2026-04-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0002_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.teacheruser'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='course_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='structures.coursecomponent'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='users.teacheruser'),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together={('teacher', 'semester', 'day', 'start_time')},
        ),
    ]
