# Generated by Django 6.0.4 on 2026-06-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['day', 'start_time']},
        ),
    ]
