# Generated by Django 6.0.3 on 2026-04-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0005_enrollement_unique_enrollment'),
        ('timetable', '0001_initial'),
        ('users', '0002_matriculecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='course_component',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='teacher',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='structures.semester')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.coursecomponent')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.schedule')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacheruser')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
