# Generated by Django 6.0.4 on 2026-04-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='unique_active_school_year'), models.UniqueConstraint(condition=models.Q(('status', 'UPCOMING')), fields=('status',), name='unique_upcoming_school_year')],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='structures.formation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='structures.level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='structures.semester')),
            ],
            options={
                'ordering': ['semester__order', 'code'],
                'unique_together': {('formation', 'level', 'semester', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELIBERATING', 'En délibération'), ('PROMOTED', 'Promu'), ('REPEAT', 'Redoublant'), ('EXCLUDED', 'Exclu')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.formation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.level')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='users.studentuser')),
            ],
            options={
                'unique_together': {('student', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('volume_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='users.teacheruser')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='structures.courseunit')),
            ],
            options={
                'ordering': ['course_unit__semester__order', 'code'],
                'unique_together': {('course_unit', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FormationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_levels', to='structures.formation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_levels', to='structures.level')),
            ],
            options={
                'unique_together': {('formation', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LevelSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_semesters', to='structures.level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level_semesters', to='structures.semester')),
            ],
            options={
                'ordering': ['semester__order'],
                'unique_together': {('level', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('PASSED', 'Validé'), ('FAILED', 'Échoué')], default='IN_PROGRESS', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.semester')),
                ('student_school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.studentschoolyear')),
            ],
            options={
                'ordering': ['semester__order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student_school_year',), name='unique_current_enrollment')],
                'unique_together': {('student_school_year', 'semester')},
            },
        ),
    ]
