# Generated by Django 6.0.4 on 2026-04-26 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_modules', to='users.teacheruser'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='structures.courseunit'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='structures.formation'),
        ),
        migrations.AddField(
            model_name='formationlevel',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_levels', to='structures.formation'),
        ),
        migrations.AddField(
            model_name='formationlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_levels', to='structures.level'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='unique_active_school_year'),
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'UPCOMING')), fields=('status',), name='unique_upcoming_school_year'),
        ),
        migrations.AddField(
            model_name='semester',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='structures.level'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='studentschoolyear',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.formation'),
        ),
        migrations.AddField(
            model_name='studentschoolyear',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.level'),
        ),
        migrations.AddField(
            model_name='studentschoolyear',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_school_years', to='structures.schoolyear'),
        ),
        migrations.AddField(
            model_name='studentschoolyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='structures.studentschoolyear'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course_unit', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='formationlevel',
            unique_together={('formation', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='courseunit',
            unique_together={('formation', 'semester', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='studentschoolyear',
            unique_together={('student', 'school_year')},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student_school_year',), name='unique_current_enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student_school_year', 'semester')},
        ),
    ]
