# Generated by Django 6.0.3 on 2026-04-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomponent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacheruser'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollements', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='semester',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.formation'),
        ),
        migrations.AddField(
            model_name='semester',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.level'),
        ),
        migrations.AddField(
            model_name='enrollement',
            name='Semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollements', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachingunits', to='structures.semester'),
        ),
        migrations.AddField(
            model_name='coursecomponent',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='structures.teachingunit'),
        ),
    ]
