# Generated by Django 6.0.4 on 2026-04-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseunit',
            name='coefficient',
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_units', to='structures.formation'),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_units', to='structures.semester'),
        ),
    ]
