# Generated by Django 6.0.4 on 2026-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='credits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='period',
            field=models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second')], default='FIRST', max_length=10),
        ),
    ]
