# Generated by Django 6.0.3 on 2026-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
