# Generated by Django 6.0.4 on 2026-05-02 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_remove_courseunit_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='min_val_score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
