# Generated by Django 6.0.3 on 2026-04-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_remove_level_name_level_number_alter_level_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollement',
            old_name='Semester',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='coursecomponent',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='structures.teachingunit'),
        ),
    ]
