# Generated by Django 6.0.3 on 2026-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_rename_semester_enrollement_semester_and_more'),
        ('users', '0002_matriculecounter'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollement',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='unique_enrollment'),
        ),
    ]
