# Generated by Django 6.0.4 on 2026-05-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audience',
            name='Formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.formation'),
        ),
        migrations.AddField(
            model_name='audience',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='audience',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.level'),
        ),
        migrations.AddField(
            model_name='audience',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.schoolyear'),
        ),
        migrations.AddField(
            model_name='read',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='read',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
