# Generated by Django 6.0.4 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculecounter',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='matriculecounter',
            unique_together={('role', 'mention')},
        ),
    ]
